### PR TITLE
categories - added title acps for categories and dropped projects fro…

### PR DESCRIPTION
**Pull request by jen-p**
…m open source

### CODE REVIEW

**Comment by craigmcginley** [comment]
Deploy preview for *loving-austin-5f2eff* ready!

Built with commit 836a081bd642f83179788ac8d2bfb4d08a26281c

https://deploy-preview-113--loving-austin-5f2eff.netlify.com

**Comment by craigmcginley** [comment]
I thought "Patient Engagement" was the outlier here. As far as I can tell, we've been doing first word capitalized and none of the rest, for titles, across the site. I assumed this was a design choice @sel2sm? But might be grammatically wrong.

**Comment by jen-p** [comment]
Used title caps, because below in the work cards, we list some with multiple categories, so it looked weird to have non-title-caps used (Care management, Patient engagement). Either format is grammatically correct, just comes down to preferences

**Comment by craigmcginley** [comment]
Works for me

**Pull request merged**
